apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.db_cofigmap.name }}
  labels:
    {{- include "lebedev-transaction.labels" . | nindent 4 }}
data:
  db_host: {{ .Values.db_cofigmap.data.db_host }}
  db_port: {{ .Values.db_cofigmap.data.db_port | toString }}
  db_schema: {{ .Values.db_cofigmap.data.db_schema }}
