apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db_secret.name }}
  labels:
    {{- include "lebedev-transaction.labels" . | nindent 4 }}
data:
  db_user: {{ .Values.db_secret.data.db_user }}
  db_password: {{ .Values.db_secret.data.db_password }}
  db_name: {{ .Values.db_secret.data.db_name }}
