apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lebedev-transaction.fullname" . }}
  labels:
    {{- include "lebedev-transaction.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lebedev-transaction.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lebedev-transaction.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SERVICE_NAME
              value: "{{ .Values.service_name }}"

          # secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db_secret.name }}
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db_secret.name }}
                  key: db_password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db_secret.name }}
                  key: db_name

            # Configmap
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.db_cofigmap.name }}
                  key: db_host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.db_cofigmap.name }}
                  key: db_port
            - name: DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                    name: {{ .Values.db_cofigmap.name }}
                    key: db_schema

            # Jaeger
            - name: JAEGER_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.jaeger_cofigmap.name }}
                  key: jaeger_host
            - name: JAEGER_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.jaeger_cofigmap.name }}
                  key: jaeger_port
