apiVersion: apps/v1
kind: Deployment
metadata:
  name: lebedev-transaction-deployment
  labels:
    app: lebedev-transaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lebedev-transaction
  template:
    metadata:
      labels:
        app: lebedev-transaction
    spec:
      containers:
        - name: lebedev-transaction-container
          image: kotbegemott/transaction_service:4
          ports:
            - containerPort: 8002
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /ready
              port: 8002
            initialDelaySeconds: 15
            periodSeconds: 2
            successThreshold: 2
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /live
              port: 8002
            initialDelaySeconds: 15
            periodSeconds: 2
            failureThreshold: 5
          env:
            # - name: DB_USER
            #   valueFrom:
            #     secretKeyRef:
            #       name: lebedev-database-secret
            #       key: db_user
            # - name: DB_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: lebedev-database-secret
            #       key: db_password
            # - name: DB_NAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: lebedev-database-secret
            #       key: db_name

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: lebedev-database-configmap
                  key: db_host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: lebedev-database-configmap
                  key: db_port
            - name: DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: lebedev-database-configmap
                  key: db_schema

            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: lebedev-database-configmap
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: lebedev-database-configmap
                  key: db_password
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: lebedev-database-configmap
                  key: db_name
