apiVersion: batch/v1
kind: Job
metadata:
  name: lebedev-migration
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: lebedev-migration-container
        image: kotbegemott/transaction_service:4
        command: ['alembic', 'upgrade', 'head']
        env:
        # database (secret)
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: lebedev-database-secret
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lebedev-database-secret
              key: db_password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: lebedev-database-secret
              key: db_name

        # database (public)
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: lebedev-database-configmap
              key: db_host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: lebedev-database-configmap
              key: db_port
        - name: DB_SCHEMA
          valueFrom:
            configMapKeyRef:
              name: lebedev-database-configmap
              key: db_schema
