apiVersion: v1
kind: Pod
metadata:
  name: lebedev-transaction-pod
spec:
  restartPolicy: Never
  containers:
    - name: lebedev-transaction-container
      image: kotbegemott/transaction_service:4
      ports:
        - containerPort: 8002
      resources:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "200Mi"
          cpu: "200m"
      readinessProbe:
        httpGet:
          path: /ready
          port: 8002
        initialDelaySeconds: 15
        periodSeconds: 2
        successThreshold: 2
        failureThreshold: 5
      livenessProbe:
        httpGet:
          path: /live
          port: 8002
        initialDelaySeconds: 15
        periodSeconds: 2
        failureThreshold: 5
